name: Feature branch push workflow

on:
    push:
        branches:
            - feature

jobs:

    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Push to feature branch"
