name: Feature branch pull request workflow

on:
    pull_request:
        branches:
            - feature

jobs:

    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Feature branch pull request"
            - run: python main.py
              shell: python