name: Feature branch push workflow

on:
    push:
        branches:
            - feature

jobs:

    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Push to feature branch"
            - uses: actions/checkout@v2
            - run: ls -l
            - run: python main.py
